app/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.dashboard,name="dashboard"),

    path('pages/buttons', views.buttons,name="buttons"),
    path('pages/elements', views.elements,name="elements"),
    path('pages/table', views.table,name="table"),
    path('pages/chart', views.chart,name="chart"),
    path('pages/icons', views.icons,name="icons"),
    path('pages/typography', views.typography,name="typography"),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls',namespace='web')),
    path('app/',include('app.urls',namespace='app')),
    path('accounts/', include('registration.backends.default.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
]

app/models.py
from django.db import models

# Create your models here.

web/models.py
from django.db import models

# Create your models here.
SOCIAL_CHOICES = (
	('android', 'android'),('apple', 'apple'),('behance', 'behance'),('dribbble', 'dribbble'),('envelope', 'email'),
	('facebook', 'facebook'),('flickr', 'flickr'),('foursquare', 'foursquare'),('google', 'google'),
	('instagram', 'instagram'),('linkedin', 'linkedin'),('meetup', 'meetup'),('pinterest', 'pinterest'),
	('reddit', 'reddit'),('rss', 'RSS'),('soundcloud', 'soundcloud'),('snapchat-ghost', 'snapchat'),
	('skype', 'skype'),('spotify', 'spotify'),('telegram', 'telegram'),('tumblr', 'tumblr'),('twitter', 'twitter'),
	('vimeo', 'vimeo'),('whatsapp', 'whatsapp'),('yahoo', 'yahoo'),('youtube-play', 'youtube'),
)

class Social(models.Model):
	order = models.IntegerField(unique=True)
	media = models.CharField(max_length=100,choices=SOCIAL_CHOICES)
	link = models.CharField(max_length=150)

	class Meta:
		ordering = ('order', )
		verbose_name = ('Social Media')
		verbose_name_plural = ('Social Medias')

	def __str__(self):
		return str(self.media)

app/views.py
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import json


def dashboard(request):
    context = {
        'is_dashboard' : True,
        'is_need_chart' : True
    }
    return render(request, 'app/index.html',context)


def buttons(request):
    return render(request,'app/pages/buttons.html',)
def elements(request):
    context = {'is_need_file_upload' : True}
    return render(request,'app/pages/elements.html',)
def table(request):
    return render(request,'app/pages/table.html',)
def chart(request):
    context = {'is_need_chart' : True}
    return render(request,'app/pages/chart.html',context)
def icons(request):
    return render(request,'app/pages/icons.html',)
def typography(request):
    return render(request,'app/pages/typography.html',)

web/views.py
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import json


def index(request):
    context = {
        "is_index" : True
    }
    return render(request, 'web/index.html',context)


def about(request):
    context = {
        "is_about" : True
    }
    return render(request, 'web/about.html',context)

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>Admin</title>
        <link rel="stylesheet" href="{% static 'app/vendors/mdi/css/materialdesignicons.min.css' %}" />
        <link rel="stylesheet" href="{% static 'app/vendors/css/vendor.bundle.base.css' %}" />
        <link rel="stylesheet" href="{% static 'app/css/style.css' %}" />
        <link rel="shortcut icon" href="{% static 'app/images/favicon.ico' %}" />
    </head>
    <body>
        <div class="container-scroller">
            {% include 'app/partials/navbar.html' %}
            <div class="container-fluid page-body-wrapper">
                {% include 'app/partials/sidebar.html' %}
                <div class="main-panel">

                    {% block content %}
                    {% endblock content %}

                    {% include 'app/partials/footer.html' %}
                </div>
                <!-- main-panel ends -->
            </div>
            <!-- page-body-wrapper ends -->
        </div>
        <!-- container-scroller -->

        <script src="{% static 'app/vendors/js/vendor.bundle.base.js' %}"></script>
        {% if is_need_chart %}<script src="{% static 'app/vendors/chart.js/Chart.min.js' %}"></script>{% endif %}
        <script src="{% static 'app/js/off-canvas.js' %}"></script>
        <script src="{% static 'app/js/hoverable-collapse.js' %}"></script>
        <script src="{% static 'app/js/misc.js' %}"></script>
        {% if is_dashboard %}
        <script src="{% static 'app/js/dashboard.js' %}"></script>
        <script src="{% static 'app/js/todolist.js' %}"></script>
        {% endif %}
        {% if is_need_chart %}<script src="{% static 'app/js/chart.js' %}"></script>{% endif %}
        {% if is_need_file_upload %}<script src="{% static 'app/js/file-upload.js' %}"></script>{% endif %}
    </body>
</html>

templates/app/pages/chart.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title"> Chart-js </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Charts</a></li>
                <li class="breadcrumb-item active" aria-current="page">Chart-js</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Line chart</h4>
                    <canvas id="lineChart" style="height:250px"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Bar chart</h4>
                    <canvas id="barChart" style="height:230px"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Area chart</h4>
                    <canvas id="areaChart" style="height:250px"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Doughnut chart</h4>
                    <canvas id="doughnutChart" style="height:250px"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Pie chart</h4>
                    <canvas id="pieChart" style="height:250px"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Scatter chart</h4>
                    <canvas id="scatterChart" style="height:250px"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- content-wrapper ends -->
{% endblock content %}

templates/app/partials/footer.html
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © {% now 'Y' %} <a href="#" target="_blank">Bootstrap</a>. All rights reserved.</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
</footer>

templates/app/partials/navbar.html
{% load static %}
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="{% url 'app:dashboard' %}"><img src="{% static 'app/images/logo.svg' %}" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="{% url 'app:dashboard' %}"><img src="{% static 'app/images/logo-mini.svg' %}" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
        <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
                <div class="input-group">
                    <div class="input-group-prepend bg-transparent">
                        <i class="input-group-text border-0 mdi mdi-magnify"></i>
                    </div>
                    <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
                </div>
            </form>
        </div>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <div class="nav-profile-img">
                        <img src="{% static 'app/images/faces/face1.jpg' %}" alt="image">
                        <span class="availability-status online"></span>
                    </div>
                    <div class="nav-profile-text">
                        <p class="mb-1 text-black">David Greymaax</p>
                    </div>
                </a>
                <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-cached mr-2 text-success"></i> Activity Log </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-logout mr-2 text-primary"></i> Signout </a>
                </div>
            </li>
            <li class="nav-item d-none d-lg-block full-screen-link">
                <a class="nav-link">
                    <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <i class="mdi mdi-email-outline"></i>
                    <span class="count-symbol bg-warning"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                    <h6 class="p-3 mb-0">Messages</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="{% static 'app/images/faces/face4.jpg' %}" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>
                            <p class="text-gray mb-0"> 1 Minutes ago </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="{% static 'app/images/faces/face2.jpg' %}" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>
                            <p class="text-gray mb-0"> 15 Minutes ago </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="{% static 'app/images/faces/face3.jpg' %}" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>
                            <p class="text-gray mb-0"> 18 Minutes ago </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#"><h6 class="p-3 mb-0 text-center">4 new messages</h6></a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="mdi mdi-bell-outline"></i>
                    <span class="count-symbol bg-danger"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                    <h6 class="p-3 mb-0">Notifications</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-success">
                                <i class="mdi mdi-calendar"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Event today</h6>
                            <p class="text-gray ellipsis mb-0"> Just a reminder that you have an event today </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-warning">
                                <i class="mdi mdi-settings"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Settings</h6>
                            <p class="text-gray ellipsis mb-0"> Update dashboard </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-info">
                                <i class="mdi mdi-link-variant"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>
                            <p class="text-gray ellipsis mb-0"> New admin wow! </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#"><h6 class="p-3 mb-0 text-center">See all notifications</h6></a>
                </div>
            </li>
            <li class="nav-item nav-logout d-none d-lg-block">
                <a class="nav-link" href="#">
                    <i class="mdi mdi-power"></i>
                </a>
            </li>

        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

templates/app/partials/sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="{% static 'app/images/faces/face1.jpg' %}" alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">David Grey. H</span>
                    <span class="text-secondary text-small">Project Manager</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'app:dashboard' %}">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                <span class="menu-title">Basic UI Elements</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi-crosshairs-gps menu-icon"></i>
            </a>
            <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="{% url 'app:buttons' %}">Buttons</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'app:typography' %}">Typography</a></li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'app:icons' %}">
                <span class="menu-title">Icons</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'app:elements' %}">
                <span class="menu-title">Forms</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'app:chart' %}">
                <span class="menu-title">Charts</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'app:table' %}">
                <span class="menu-title">Tables</span>
                <i class="mdi mdi-table-large menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#general-pages" aria-expanded="false" aria-controls="general-pages">
                <span class="menu-title">Sample Pages</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi-medical-bag menu-icon"></i>
            </a>
            <div class="collapse" id="general-pages">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html"> Login </a></li>
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/error-404.html"> 404 </a></li>
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/error-500.html"> 500 </a></li>
                </ul>
            </div>
        </li>
        <li class="nav-item sidebar-actions">
            <span class="nav-link">
                <div class="border-bottom">
                    <h6 class="font-weight-normal mb-3">Projects</h6>
                </div>
                <button class="btn btn-block btn-lg btn-gradient-primary mt-4">+ Add a project</button>
                <div class="mt-4">
                    <div class="border-bottom">
                        <p class="text-secondary">Categories</p>
                    </div>
                    <ul class="gradient-bullet-list mt-4">
                        <li>Free</li>
                        <li>Pro</li>
                    </ul>
                </div>
            </span>
        </li>
    </ul>
</nav>

templates/web/about.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}About Us{% endblock%}

{% block content %}
-------- content here --------
{% endblock%}

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock%}</title>
    <link rel="stylesheet" href="{% static 'main/main.css' %}">
</head>
<body>
    <div class="ajax_loader"></div>
    {% block content %}

    {% endblock%}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
    <link rel="stylesheet" href="{% static 'main/script.css' %}">
</body>
</html>

templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Home{% endblock%}

{% block content %}
-------- content here --------
{% endblock%}